services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/prisma/dev.db
    command: sh -c "
      if [ ! -f node_modules/.prisma/client/index.js ]; then
        echo 'Gerando Prisma Client...';
        npx prisma generate;
      fi &&
      npx prisma migrate deploy &&
      npm run dev
      "